### ISSUE TITLE
Getting "empty collection" exception - no other information

### ISSUE THREAD

**Issue by armahajan** [PredictionIO/template-scala-parallel-universal-recommendation#2]
I am getting Exception in thread "main" java.lang.UnsupportedOperationException: empty collection on step 41 or so while the engine is training. There is no other debugging information. What could be the issue here?

I have $set users, items and view and purchase events and made sure the data is logically connected between these.

Thanks in advance for your help!

Regards,
Akshay Mahajan

**Comment by armahajan** [comment]
Full trace is below:

ubuntu@ip-172-31-15-215:/ignpredictionio/univrecoengine$ pio train
[INFO] [Console$] Using existing engine manifest JSON at /ignpredictionio/univre                                                                                        coengine/manifest.json
[INFO] [Runner$] Submission command: /opt/spark-1.3.1-bin-hadoop2.6/bin/spark-su                                                                                        bmit --class io.prediction.workflow.CreateWorkflow --jars file:/ignpredictionio/                                                                                        univrecoengine/target/scala-2.10/template-scala-parallel-recommendation-assembly                                                                                        -0.1-SNAPSHOT-deps.jar,file:/ignpredictionio/univrecoengine/target/scala-2.10/te                                                                                        mplate-scala-parallel-recommendation_2.10-0.1-SNAPSHOT.jar --files file:/opt/Pre                                                                                        dictionIO/conf/log4j.properties --driver-class-path /opt/PredictionIO/conf file:                                                                                        /opt/PredictionIO/lib/pio-assembly-0.9.3.jar --engine-id IoT1GkpuNNSXxhnYgNPJqwU                                                                                        4nMCIu6L5 --engine-version 7dd4d5b4a4d72963d3bc159242c53c73b20cad21 --engine-var                                                                                        iant file:/ignpredictionio/univrecoengine/engine.json --verbosity 0 --json-extra                                                                                        ctor Both --env PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta                                                                                        ,PIO_FS_BASEDIR=/home/ubuntu/.pio_store,PIO_HOME=/opt/PredictionIO,PIO_FS_ENGINE                                                                                        SDIR=/home/ubuntu/.pio_store/engines,PIO_STORAGE_SOURCES_PGSQL_URL=jdbc:postgres                                                                                        ql://localhost/pio,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=PGSQL,PIO_STORAGE_RE                                                                                        POSITORIES_MODELDATA_SOURCE=PGSQL,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_ev                                                                                        ent,PIO_STORAGE_SOURCES_PGSQL_PASSWORD=pio,PIO_STORAGE_SOURCES_PGSQL_TYPE=jdbc,P                                                                                        IO_FS_TMPDIR=/home/ubuntu/.pio_store/tmp,PIO_STORAGE_SOURCES_PGSQL_USERNAME=pio,                                                                                        PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENT                                                                                        DATA_SOURCE=PGSQL,PIO_CONF_DIR=/opt/PredictionIO/conf
[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(ignunivreco,List(purchase,                                                                                         view, add-to-cart, location, device)))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDri                                                                                        ver@ip-172-31-15-215.us-west-2.compute.internal:40870]
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.ignitiv.DataSource@3a7d313
[INFO] [Engine$] Preparator: com.ignitiv.Preparator@4c19fd21
[INFO] [Engine$] AlgorithmList: List(com.ignitiv.URAlgorithm@314b9e72)
[INFO] [Engine$] Data santiy check is on.
[INFO] [Engine$] com.ignitiv.TrainingData does not support data sanity check. Sk                                                                                        ipping check.
Exception in thread "main" java.lang.UnsupportedOperationException: empty collec                                                                                        tion
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:902)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:902)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.reduce(RDD.scala:902)
        at org.apache.spark.rdd.DoubleRDDFunctions.sum(DoubleRDDFunctions.scala:                                                                                        34)
        at org.apache.mahout.sparkbindings.drm.CheckpointedDrmSpark.computeNRow(                                                                                        CheckpointedDrmSpark.scala:195)
        at org.apache.mahout.sparkbindings.drm.CheckpointedDrmSpark.nrow$lzycomp                                                                                        ute(CheckpointedDrmSpark.scala:57)
        at org.apache.mahout.sparkbindings.drm.CheckpointedDrmSpark.nrow(Checkpo                                                                                        intedDrmSpark.scala:57)
        at org.apache.mahout.sparkbindings.drm.CheckpointedDrmSpark.newRowCardin                                                                                        ality(CheckpointedDrmSpark.scala:217)
        at org.apache.mahout.math.indexeddataset.IndexedDataset$class.newRowCard                                                                                        inality(IndexedDataset.scala:57)
        at org.apache.mahout.sparkbindings.indexeddataset.IndexedDatasetSpark.ne                                                                                        wRowCardinality(IndexedDatasetSpark.scala:37)
        at com.ignitiv.Preparator$$anonfun$2.apply(Preparator.scala:36)
        at com.ignitiv.Preparator$$anonfun$2.apply(Preparator.scala:34)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike                                                                                        .scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike                                                                                        .scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.ignitiv.Preparator.prepare(Preparator.scala:34)
        at com.ignitiv.Preparator.prepare(Preparator.scala:10)
        at io.prediction.controller.PPreparator.prepareBase(PPreparator.scala:34                                                                                        )
        at io.prediction.controller.Engine$.train(Engine.scala:667)
        at io.prediction.controller.Engine.train(Engine.scala:174)
        at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
        at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:246)
        at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSub                                                                                        mit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:16                                                                                        6)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
ubuntu@ip-172-31-15-215:/ignpredictionio/univrecoengine$

**Comment by tom-chan** [comment]
Can you implement some sanity check as described in https://docs.prediction.io/customize/troubleshooting/#sanity-check and see if any of your training data is empty?

**Comment by armahajan** [comment]
Ok, will do that. But before, there are some issues with documentation, the following command does not work since the .py files are not in data directory but are in examples directory. Also the .py file names are different.

python data/import_handmade.py --access_key **your-access-key** should be changed to python examples/import_handmade_eventserver.py --access_key **your-access-key**

Even with the sample data provided, I cleaned up all my events, loaded from import_handmade_eventserver.py and did pio build followed by pio train, still it failed saying empty collection. Could you have a look? Meanwhile I will implement SanityCheck. Thank you!

**Comment by armahajan** [comment]
ok - I found that add-to-cart was declared in my eventNames but did not have a single event of that type. After removing, training part gets through. Now getting another exception. IS this because no previous indexes have been created to delete? In that case code should handle empty index collection case? Or something similar. Full trace below.

[INFO] [URModel] Deleting index: /urindex/item
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
        at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:86)
        at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:77)
        at org.elasticsearch.client.support.AbstractIndicesAdminClient.exists(AbstractIndicesAdminClient.java:165)
        at com.ignitiv.esClient$.deleteIndex(esClient.scala:30)
        at com.ignitiv.URModel.save(URModel.scala:72)
        at com.ignitiv.URModel.save(URModel.scala:15)
        at io.prediction.controller.P2LAlgorithm.makePersistentModel(P2LAlgorithm.scala:111)
        at io.prediction.controller.Engine$$anonfun$makeSerializableModels$2.apply(Engine.scala:294)
        at io.prediction.controller.Engine$$anonfun$makeSerializableModels$2.apply(Engine.scala:293)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at io.prediction.controller.Engine.makeSerializableModels(Engine.scala:293)
        at io.prediction.controller.Engine.train(Engine.scala:185)
        at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
        at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:246)
        at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by armahajan** [comment]
I do have es.index.auto.create with value true in my engine.json

**Comment by armahajan** [comment]
Ok - installed and enabled elasticsearch (was commented in my pio installation) and got the engine to train successfully.

**Comment by kucukil** [comment]
I do have the same elasticsearch exception, es.index.auto.create is true in my engine.json elasticsearch is configured as metadata storage. I have changed its cluster name, may it be the problem?

**Comment by armahajan** [comment]
Could be. Have you used the same cluster name in /opt/PredictionIO/conf/pio-env.sh file for PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME property?

**Comment by kucukil** [comment]
Yes, I have also changed it, i guess predictionio uses elasticsearch for metadata storage only.
Do I have to set PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE property as elasticsearch instead of localfs, too?

PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta
PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH

PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event
PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE

PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model
PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS

**Comment by kucukil** [comment]
The exception is below;

[INFO] [URModel] Deleting index: /urindex/songs  
[WARN] [transport] [Dmitri Bukharin] node [#transport#-1][ubuntu][inet[localhost/127.0.0.1:9300]] not part of the cluster Cluster [elasticsearch], ignoring...
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)

**Comment by pferrel** [comment]
The current template for the UR requires a localhost version of Elasticsearch. Fix coming soon in v0.2.0 branch to be published next week.

Try setting ES_CONF_DIR in pio-env to point to you local installation of the elasticsearch/config directory. If the cluster is set up there it **might** work. As I said, fix coming soon.
